config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/coments/:id', to: 'dashboard#show'
  end

  resources :questions do
    resource :favorites, only: [:create, :destroy]
    resources :answers
  end

  resources :records

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/mypage', to: 'users#show'
  get '/users/edit', to: 'users#edit', as: 'edit_user'
  patch '/users', to: 'users#update', as: 'user'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  post '/guest_login', to: 'session#guest_login'
  get '/logout', to: 'session#destroy'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags

  validates :title, presence: true, length: { maximum: 30 }
  validates :name, presence: true
  validates :content, presence: true, length: { minimum: 5 }

  def save_tags(tags)
    tags.each do |name|
      tag = Tag.find_or_create_by(name: name)
      self.tags << tag
    end
  end
end

app/controllers/questions_controller.rb
require 'uri'
require 'net/http'
require 'json'

class QuestionsController < ApplicationController
  def index
    if params[:tag_search].present?
      tag = Tag.find_by(name: params[:tag_search])
      @questions = tag ? tag.questions : []
    elsif params[:search].present?
      @questions = Question.where('title LIKE ? OR content LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%")
    else
      @questions = Question.includes(:tags).all
    end

    cities = ['Sapporo,jp', 'Sendai,jp', 'Tokyo,jp', 'Nagoya,jp', 'Osaka,jp', 'Fukuoka,jp', 'Naha,jp']
    @weather_data = []

    cities.each do |city|
      uri = URI("https://api.openweathermap.org/data/2.5/weather?q=#{city}&APPID=0ceca44706ea610d53a5304f3f0f3288")
      res = Net::HTTP.get_response(uri)
      body = JSON.parse(res.body)
      weather = {
        name: body['name'],
        icon: body.dig('weather', 0, 'icon')
      }
      @weather_data << weather
    end
  end

  def show
    @question = Question.includes(:tags).find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = session[:user_id]

    tag_list = params[:tag_names].split(',')
    if @question.save
      @question.save_tags(tag_list)
      flash[:notice] = '質問を作成しました'
      redirect_to @question
    else
      render 'new'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:notice] = '質問を削除しました'
    if current_user&.admin?
      # 管理者用のリダイレクト先
      redirect_to admin_dashboard_path
    else
      # 通常ユーザーのリダイレクト先
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :name, :content)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/index.html.erb
<h5 class="site-guide">
  みんなの広場は、不妊治療について情報交換できる場所です<br>
  治療のことやあなたの気持ち、聞きたいこと、話したいことなんでも話しましょう
</h5>
<h1>投稿広場</h1>
<div class="question-search-area">
  <form method="get" action="<%= questions_path %>">
    <input type="text" name="search" placeholder="キーワード検索" class="question-search-input">
    <input type="text" name="tag_search" placeholder="タグ検索" class="question-search-input">
    <input type="submit" value="検索" class="search-button">
  </form>
</div>
<div class="questions-area">
  <%= link_to '新規投稿する', new_question_path, class: "btn btn-success" %>
  <% @questions.each do |q| %>
    <div class="card mb-3, container" >
      <div class="card-body">
        <h5 class="card-title"><%= q.title %></h5>
        <p class="card-subtitle mb-2 text-muted"><%= q.name %></p>
        <p class="card-text"><%= simple_format(h(q.content)) %></p>
        <% if q.tags.exists? %>
          <p>
            <i class="fa-solid fa-tag"></i>
            <% q.tags.each do |tag| %>
              <%= link_to tag.name, questions_path(tag_search: tag.name) %>
            <% end %>
          </p>
        <% end %>
        <div class="question-select-bar">
          <%= link_to "詳細", question_path(q), class:"btn" %>
          <% if current_user && current_user.already_favorited?(q) %>
            <%= link_to question_favorites_path(q), data: { "turbo-method": :delete }, class: "non-like-button" do %>
              <i class="fa-regular fa-heart" style="color: #b5838d;"></i>
            <% end %>
          <% else %>
            <%= link_to question_favorites_path(q), data: { "turbo-method": :post }, class: "like-button" do %>
              <i class="fas fa-heart" style="color: #b5838d;"></i>
            <% end %>
          <% end %>
          <span class="like-count"><%= q.favorites.count %></span>
        </div>
      </div>
    </div>
  <% end %>
</div>
<h1>今日の天気</h1>
<div class="weather-bar">
  <% @weather_data.each do |weather| %>
    <div class="weather-details">
      <h3 class="weather-name"><%= weather[:name] %></h3>
      <img src="https://openweathermap.org/img/wn/<%= weather[:icon] %>@2x.png" alt="Weather Icon" width="50">
    </div>
  <% end %>
</div>

app/views/questions/new.html.erb
<%= render 'shared/error_messages', model: @question %>
<h1>質問の新規作成</h1>
<h2>気になることや不安なこと、なんでも聞いてみよう</h2>
<div class="container question-input">
  <%= form_with model: @question, local: true,class:"container", data: { turbo: false } do |f| %>
    <div class="form-group question-title">
      <%= f.label :title %>
      <%= f.text_field :title, class:"form-control" %>
    </div>
    <div class="form-group question-name">
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="form-group question-content">
      <%= f.label :content %>
      <%= f.text_area :content, class:"form-control", size: "20x10" %>
    </div>
    <div class="form-group question-tag">
      <%= label_tag :tag_names, 'Tag (「,」で区切ると複数登録できます)' %>
      <%= text_field_tag :tag_names %>
    </div>
    <div class="question-submit">
      <%= link_to "戻る", 'javascript:history.back()', class: "btn" %>
     <%= f.submit "投稿", class: "btn" %>
    </div>
  <% end %>
</div>

app/views/questions/show.html.erb
<div class="show-area">
  <%= link_to '一覧に戻る', questions_path, class: "btn" %>
  <div class="card mb-3 container">
    <div class="card-body">
      <h5 class="card-title"><%= @question.title %></h5>
      <p class="card-subtitle mb-2 text-muted"><%= @question.name %></p>
      <p class="card-text"><%= simple_format(h(@question.content)) %></p>
      <% if @question.tags.exists?%>
        <p>
          <i class="fa-solid fa-tag"></i>
          <% @question.tags.each do |tag| %>
            <%= link_to tag.name, questions_path(tag_search: tag.name) %>
          <% end %>
        </p>
      <% end %>
      <div class="question-detail-bottom">
        <% if current_user && current_user.already_favorited?(@question)%>
          <%= link_to question_favorites_path(@question), data: { "turbo-method": :delete }, class: "non-like-button" do %>
            <i class="fa-regular fa-heart" style="color: #b5838d;"></i>
          <% end %>
        <% else %>
          <%= link_to question_favorites_path(@question), data: { "turbo-method": :post }, class: "like-button" do %>
            <i class="fas fa-heart" style="color: #b5838d;"></i>
          <% end %>
        <% end %>
        <span class="like-count"><%= @question.favorites.count %></span>
        <span>投稿日：<%= @question.created_at.strftime("%Y/%m/%d") %></span>
      </div>
    </div>
  </div>
  <h2 class="coment-title">コメントする</h2>
  <h5>
    <ul>
      <li>あなたが言われて傷つくことは禁止です</li>
      <li>Q&A以外の内容は禁止です</li>
    <ul>
  </h5>
  <div class="coment-area">
    <%= form_with model: [@question, @question.answers.build], class:"container" do |form| %>
      <div class="form-group comenter-name">
        <%= form.label :name %>
        <%= form.text_field :name, class:"form-control" %>
      </div>
      <div class="form-group coment-input">
        <%= form.label :content %>
        <%= form.text_area :content, class:"form-control", rows: 7 %>
      </div>
      <div class="coment-button">
        <%= form.submit "投稿", class: "btn" %>
      </div>
    <% end %>
  </div>
  <h2 class="coment-index">コメント一覧</h2>
  <% @question.answers.each do |answer| %>
    <% if answer.name.present? && answer.content.present? %>
      <div class="card mb-3, container" >
        <div class="card-body">
          <p class="card-subtitle mb-2 text-muted"><%= answer.name %></p>
          <p class="card-text"><%= simple_format(h(answer.content)) %></p>
          <p>回答日：<%= answer.created_at.strftime("%Y/%m/%d") %></p>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= link_to '一覧に戻る', questions_path, class: "btn" %>
</div>