config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/coments/:id', to: 'dashboard#show'
  end

  resources :questions do
    resource :favorites, only: [:create, :destroy]
    resources :answers
  end

  resources :records

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/mypage', to: 'users#show'
  get '/users/edit', to: 'users#edit', as: 'edit_user'
  patch '/users', to: 'users#update', as: 'user'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  post '/guest_login', to: 'session#guest_login'
  get '/logout', to: 'session#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :records, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def already_favorited?(question)
    favorites.exists?(question_id: question.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_to_signin, only: %i[show edit update]

  def show
    @questions = current_user.questions
    @favorites = current_user.favorites.includes(question: :favorites)
  end

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:name, :email, :password, :password_confirmation)
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = '登録しました'
      redirect_to login_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])
    user_params = params.require(:user).permit(:name, :email)
    if @user.update(user_params)
      flash[:notice] = '更新しました'
      redirect_to edit_user_path
    else
      render 'edit'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: user, url: form_url, method: form_method, class: form_class, local: true, data: { turbo: false } do |f| %>
  <div class="form-group user-name">
    <label>名前</label>
    <%= f.text_field :name, class: "form-control", size: 50 %>
  </div>
  <div class="form-group user-email">
    <label>メールアドレス</label>
    <%= f.text_field :email, class: "form-control", size: 50 %>
  </div>
  <% if local_assigns.has_key?(:password_fields) && password_fields %>
    <div class="form-group user-password">
      <label>パスワード</label>
      <%= f.password_field :password, class: "form-control", size: 50 %>
    </div>
    <div class="form-group user-password-confirmation">
      <label>パスワード確認用</label>
      <%= f.password_field :password_confirmation, class: "form-control", size: 50 %>
    </div>
  <% end %>
  <div>
    <%= link_to "戻る", 'javascript:history.back()', class: "btn" %>
    <%= f.submit submit_label, class: "btn" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'shared/error_messages', model: @user %>
<h1>会員情報更新</h1>
<%= render 'form', user: @user, form_url: user_path, form_method: :patch, form_class: "user-form", submit_label: "更新", password_fields: false %>

app/views/users/new.html.erb
<%= render 'shared/error_messages', model: @user %>
<h1>会員登録</h1>
<%= render 'form', user: @user, form_url: signup_path, form_method: :post, form_class: "user-form", submit_label: "登録", password_fields: true %>

app/views/users/show.html.erb
<h1 class="my-page-title"><%= current_user.name %>さんのマイページ</h1>
<h2 class="my-questions-title">投稿した質問</h2>
<div class="container mypage-question-contents">
  <p class="my-question-count"><%= @questions.count %>件</p>
  <% @questions.each do |question| %>
    <div class="card-body">
      <h3><%= link_to question.title, question_path(question), class: "my-question" %></h3>
      <p class="card-text">
        <%= simple_format(h(question.content)) %>
      </p>
      <%= link_to "削除", question_path(question), data: { turbo_method: "delete", turbo_confirm: "本当に削除しますか？" }, class:"btn" %>
    </div>
  <% end %>
</div>
<h2 class="my-favorite-title">お気に入り一覧</h2>
<div class="my-favorite-contents">
  <p class="my-favorite-count"><%= @favorites.count %>件</p>
  <% @favorites.each do |favorite| %>
    <div class="card-body ">
      <h3><%= link_to favorite.question.title, question_path(favorite.question), class: "my-favorite-question" %></h3>
      <p class="card-text">
        <%= simple_format(h(favorite.question.content)) %>
      </p>
      <%= link_to question_favorites_path(favorite.question), data: { "turbo-method": :delete }, class: "non-like-button" do %>
        <i class="fa-regular fa-heart" style="color: #b5838d;"></i>
      <% end %>
      <span class="like-count">
        <%= favorite.question.favorites.count %>
      </span>
    </div>
  <% end %>
</div>
<h2 class="my-acount-title">登録情報の編集</h2>
<div class="my-acount-contents">
  <% if current_user.name == "guest_login" && current_user.email == "guest@example.com"%>
    <p>ゲストユーザーは編集できません</p>
  <% else %>
    <p>名前：<%= current_user.name %></p>
    <p>メールアドレス：<%= secret_email(current_user.email) %></p>
    <%= link_to "編集", edit_user_path, class:"btn" %>
  <% end %>
</div>