config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/coments/:id', to: 'dashboard#show'
  end

  resources :questions do
    resource :favorites, only: [:create, :destroy]
    resources :answers
  end

  resources :records

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/mypage', to: 'users#show'
  get '/users/edit', to: 'users#edit', as: 'edit_user'
  patch '/users', to: 'users#update', as: 'user'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  post '/guest_login', to: 'session#guest_login'
  get '/logout', to: 'session#destroy'
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user

  validates :date, presence: true, uniqueness: true
  validates :body_temperature, presence: true
  validates :weight, presence: true
  validates :body_fat_percentage, presence: true
  validates :condition, presence: true
  validates :memo, presence: true
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :redirect_to_signin
  before_action :set_record, only: %i[show edit update destroy]

  def index
    this_month_range = Time.current.beginning_of_month..Time.current.end_of_month
    @records = Record.where(user_id: session[:user_id], date: this_month_range).order(:date)

    @weight_data = @records.where(date: this_month_range).group_by_day(:date).average(:weight)
    @body_temperature_data = @records.where(date: this_month_range).group_by_day(:date).average(:body_temperature)
    @body_fat_percentage_data = @records.where(date: this_month_range).group_by_day(:date).average(:body_fat_percentage)
  end

  def show; end

  def new
    @record = Record.new
  end

  def create
    record_params = params.require(:record).permit(
      :date, :body_temperature, :weight, :body_fat_percentage,
      :condition, :memo
    ).merge(user_id: session[:user_id])

    @record = Record.new(record_params)

    if @record.save
      flash[:notice] = '保存しました'
      redirect_to records_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    record_params = params.require(:record).permit(
      :date, :body_temperature, :weight, :body_fat_percentage,
      :condition, :memo
    )
    if @record.update(record_params)
      flash[:notice] = '記録を更新しました'
      redirect_to records_path
    else
      render 'edit'
    end
  end

  def destroy
    @record.destroy
    flash[:notice] = '記録を削除しました'
    redirect_to records_path
  end

  private

  def set_record
    @record = Record.where(user_id: session[:user_id]).find(params[:id])
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= render 'shared/error_messages', model: @record %>
<h1>体調記録の<%= type %></h1>
<%= form_with model: record, local: true,method: method, class: "record-form", data: { turbo: false } do |f| %>
  <div class="form-group record-input">
    <label>日付</label>
    <%= f.date_field :date, class: "form-control" %>
  </div>
  <div class="form-group record-input">
    <label>基礎体温</label>
    <%= f.number_field :body_temperature, class: "form-control" %>
  </div> 
  <div class="form-group record-input">
    <label>体重</label>
    <%= f.number_field :weight, class: "form-control" %>
  </div>
  <div class="form-group record-input">
    <label>体脂肪率</label>
    <%= f.number_field :body_fat_percentage, class: "form-control" %>
  </div>
  <div class="form-group record-input">
    <label>気分</label>
    <%= f.select :condition, [["大変良い!!", "大変良い!!"], ["良い", "良い"], ["悪い", "悪い"]], { include_blank: "選択して下さい" }, { class: "form-control" } %>
  </div> 
  <div class="form-group record-input"> 
    <label>日記・メモ</label>
    <%= f.text_area :memo, class: "form-control", size: "20x10" %>
  </div> 
  <div class="bottom-button">
    <%= link_to "戻る", 'javascript:history.back()', class: "btn" %>
    <%= f.submit type, class: "btn" %>
  </div>
<% end %>

app/views/records/edit.html.erb
<%= render partial: "form", locals: { type: "修正", record: @record, method: "patch" } %>

app/views/records/index.html.erb
<h1>今月の体調記録</h1>
<div class="new-record-btn">
  <%= link_to "記入する", new_record_path, class: "btn new-record-btn-text" %>
</div>
<div class="chart-box">
  <div class="button-bar">
    <button id="weight-chart" class="btn">体重</button>
    <button id="body-temperature-chart" class="btn">体温</button>
    <button id="body-body_fat_percentage-chart" class="btn">体脂肪率</button>
  </div>
  <div class="chart">
    <div class="weight-chart">
      <%= line_chart @weight_data, colors: ['#6d597a'] %> 
    </div>
    <div class="body-temperature-chart">
      <%= line_chart @body_temperature_data, colors: ['#6d597a'] %>
    </div>
    <div class="body-body_fat_percentage-chart">
      <%= line_chart @body_fat_percentage_data, colors: ['#6d597a'] %>
    </div>
  </div>
</div>
<table class="table table-striped">
  <tr>
    <th>日付</th>
    <th>基礎体温</th>
    <th>体重</th>
    <th>体脂肪率</th>
    <th></th>
  </tr>
  <% @records.each do |record| %>
  <tr>
    <td><%= record.date %></td>
    <td><%= record.body_temperature %>℃</td>
    <td><%= record.weight %>KG</td>
    <td><%= record.body_fat_percentage %>%</td>
    <td>
      <%= link_to "詳細", record_path(record), class: "btn" %>
      <%= link_to "編集", edit_record_path(record), class: "btn" %>
      <%= link_to "削除", record_path(record),data: { turbo_method: "delete", turbo_confirm: "Are you sure?" }, class:"btn" %>
    </td>
  </tr>
  <% end %>
</table>

app/views/records/new.html.erb
<%= render partial: "form", locals: { type: "登録", record: @record, method: nil} %>

app/views/records/show.html.erb
<h1>Daily Record</h1>
<table class="table table-striped">
  <tr>
    <th>日付</th>
    <td><%= @record.date %></td>
  </tr>
  <tr>
    <th>基礎体温</th>
    <td><%= @record.body_temperature %></td>
  </tr>
  <tr>
    <th>体重</th>
    <td><%= @record.weight %></td>
  </tr>
  <tr>
    <th>体脂肪率</th>
    <td><%= @record.body_fat_percentage %></td>
  </tr>
  <tr>
    <th>体調</th>
    <td><%= @record.condition %></td>
  </tr>
  <tr>
    <th>日記・メモ</th>
    <td><%= simple_format(h(@record.memo)) %></td>
  </tr>
</table>
<div class="back-button">
  <%= link_to "戻る", 'javascript:history.back()', class: "btn" %>
</div>