config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/coments/:id', to: 'dashboard#show'
  end

  resources :questions do
    resource :favorites, only: [:create, :destroy]
    resources :answers
  end

  resources :records

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/mypage', to: 'users#show'
  get '/users/edit', to: 'users#edit', as: 'edit_user'
  patch '/users', to: 'users#update', as: 'user'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  post '/guest_login', to: 'session#guest_login'
  get '/logout', to: 'session#destroy'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :name, presence: true
  validates :content, presence: true, length: { minimum: 5 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags

  validates :title, presence: true, length: { maximum: 30 }
  validates :name, presence: true
  validates :content, presence: true, length: { minimum: 5 }

  def save_tags(tags)
    tags.each do |name|
      tag = Tag.find_or_create_by(name: name)
      self.tags << tag
    end
  end
end

app/models/question_tag.rb
class QuestionTag < ApplicationRecord
  belongs_to :question
  belongs_to :tag
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user

  validates :date, presence: true, uniqueness: true
  validates :body_temperature, presence: true
  validates :weight, presence: true
  validates :body_fat_percentage, presence: true
  validates :condition, presence: true
  validates :memo, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :question_tags, dependent: :destroy
  has_many :questions, through: :question_tags

  validates :name, presence: true, length: { maximum: 20 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :records, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def already_favorited?(question)
    favorites.exists?(question_id: question.id)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @question.answers.create(answer_params)
    redirect_to question_path(@question)
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    if current_user&.admin?
      # 管理者用のリダイレクト先
      redirect_to admin_path(@question)
    else
      # 通常ユーザーのリダイレクト先
      redirect_to @question
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:name, :content)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    if current_user
      @favorite = current_user.favorites.create(question_id: params[:question_id])
      redirect_back(fallback_location: root_path)
      flash[:notice] = 'お気に入りに追加しました'
    else
      flash[:alert] = 'お気に入り機能にはログインが必要です'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @question = Question.find(params[:question_id])
    @favorite = current_user.favorites.find_by(question_id: @question.id)
    @favorite.destroy
    flash[:notice] = 'お気に入りを削除しました'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :redirect_to_signin
  before_action :set_record, only: %i[show edit update destroy]

  def index
    this_month_range = Time.current.beginning_of_month..Time.current.end_of_month
    @records = Record.where(user_id: session[:user_id], date: this_month_range).order(:date)

    @weight_data = @records.where(date: this_month_range).group_by_day(:date).average(:weight)
    @body_temperature_data = @records.where(date: this_month_range).group_by_day(:date).average(:body_temperature)
    @body_fat_percentage_data = @records.where(date: this_month_range).group_by_day(:date).average(:body_fat_percentage)
  end

  def show; end

  def new
    @record = Record.new
  end

  def create
    record_params = params.require(:record).permit(
      :date, :body_temperature, :weight, :body_fat_percentage,
      :condition, :memo
    ).merge(user_id: session[:user_id])

    @record = Record.new(record_params)

    if @record.save
      flash[:notice] = '保存しました'
      redirect_to records_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    record_params = params.require(:record).permit(
      :date, :body_temperature, :weight, :body_fat_percentage,
      :condition, :memo
    )
    if @record.update(record_params)
      flash[:notice] = '記録を更新しました'
      redirect_to records_path
    else
      render 'edit'
    end
  end

  def destroy
    @record.destroy
    flash[:notice] = '記録を削除しました'
    redirect_to records_path
  end

  private

  def set_record
    @record = Record.where(user_id: session[:user_id]).find(params[:id])
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      flash[:notice] = 'ログインしました'
      session[:user_id] = user.id
      if current_user&.admin?
        redirect_to admin_dashboard_path
      else
        redirect_to mypage_path
      end
    else
      flash.now[:alert] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

  def guest_login
    user = User.find_by(email: 'guest@example.com')
    session[:user_id] = user.id
    redirect_to mypage_path
    flash[:notice] = 'ゲストとしてログインしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_to_signin, only: %i[show edit update]

  def show
    @questions = current_user.questions
    @favorites = current_user.favorites.includes(question: :favorites)
  end

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:name, :email, :password, :password_confirmation)
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = '登録しました'
      redirect_to login_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])
    user_params = params.require(:user).permit(:name, :email)
    if @user.update(user_params)
      flash[:notice] = '更新しました'
      redirect_to edit_user_path
    else
      render 'edit'
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def secret_email(email)
    user, _secret = email.split('@')
    "#{user}@XXXXX.XXX"
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>みんなの広場</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/b0b54160e3.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-light">
      <div class="navbar-brand">
        <% if session[:user_id].present? %>
          <%= link_to "みんなの広場", records_path, class: "brand-name" %>
        <% else %>
          <%= link_to "みんなの広場", questions_path, class: "brand-name" %>
        <% end %>
      </div>
      <div class="top-bar">
        <%= link_to "Q&A", questions_path, class: "btn" %>
        <% if session[:user_id].present? %>
          <%= link_to "体調管理", records_path, class: "btn" %>
          <%= link_to "マイページ", mypage_path, class: "btn" %>
          <% if current_user&.admin? %>
            <%= link_to "管理人ページ", admin_dashboard_path, class: "btn" %>
          <% end %>
          <%= link_to "ログアウト", logout_path, class: "btn" %>
        <% else %>
          <%= link_to "ゲストログイン", guest_login_path, data: { "turbo-method": :post }, class: "btn" %>
          <%= link_to "ログイン", login_path, class: "btn"%>
          <%= link_to "会員登録", signup_path, class: "btn"%>
        <% end %>
      </div>
    </nav>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <%= yield %>
      <% if session[:user_id].present? %>
        <%= link_to "↑ ページ上部に戻る", "#", class: "back-to-top" %>
      <% end %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>